# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  
    app_store_connect_api_key(
      key_id: "#{ENV["APP_STORE_CONNECT_KEY_ID"]}",
      issuer_id: "#{ENV["APP_STORE_CONNECT_ISSUER_ID"]}",
      key_content: "#{ENV["APP_STORE_CONNECT_KEY"]}",
      is_key_content_base64: true
    )
  
    today = Time.now.strftime("%Y%m%d")
    
    current_build_number = "#{latest_testflight_build_number}"

    if current_build_number.length == 9
      current_date = current_build_number[0,8]         # 앞 8자리가 날짜
      current_count = current_build_number[8].to_i      # 마지막 1자리가 숫자
    else
      # 빌드 넘버가 없거나 형식이 다르면 초기화
      current_date = ""
      current_count = 0
    end

    if current_date == today
      next_count = current_count + 1
    else
      next_count = 1
    end

    new_build_number = "#{today}#{next_count}"
    
    increment_build_number(
      xcodeproj: "Run Mile.xcodeproj",
      build_number: new_build_number
    )
    
    # notification(
    #   subtitle: "Build Number: #{new_build_number}",
    #   message: "테스트 플라이트 배포 준비"
    # )
    
    slack(
      message: "Build Number: #{new_build_number} 배포 준비 시작",
      slack_url: "https://hooks.slack.com/services/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"
    )
    
    match(type: "appstore")
    
    slack(
      message: "Build Number: #{new_build_number} 인증서 준비 완료",
      slack_url: "https://hooks.slack.com/services/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"
    )
    
    build_app(
      scheme: "Run Mile",
      xcodebuild_formatter: "xcpretty",
      export_options: {
        provisioningProfiles: {
          "com.mooni.Run-Mile" => "com.mooni.Run-Mile AppStore"
        }
      }
    )
    
    slack(
      message: "Build Number: #{new_build_number} 아카이브 완료",
      slack_url: "https://hooks.slack.com/services/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"
    )
    
    upload_to_testflight
    
    # notification(
    #   subtitle: "Testflight 배포 성공!",
    #   message: "Build Number : #{new_build_number}, 테스트 플라이트 배포에 성공했습니다!"
    # )
    
    slack(
      message: "Build Number: #{new_build_number} 배포 성공!",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end
  
  error do |lane, exception, options|
  #   notification(
  #   subtitle: "Testflight 배포 중 오류가 발생했습니다.",
  #   message: "#{exception}"
  #   )
    slack(
      message: "Testflight 배포 중 오류가 발생했습니다. #{exception}",
      slack_url: "https://hooks.slack.com/services/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"
    )
  end
end
